# Generated by Django 5.1.4 on 2025-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watchlist_username",
            field=models.CharField(max_length=200),
        ),
    ]
