# Generated by Django 5.1.4 on 2025-02-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_watchlist_watchlist_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watchlist_username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Username",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
