# Generated by Django 5.1.4 on 2025-02-06 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_watchlist_watchlist_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="Watchlist_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.auction_listing",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="bidder_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="bidding_amount",
            field=models.IntegerField(default=0),
        ),
    ]
