# Generated by Django 5.1.4 on 2025-02-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_watchlist_listing_bid_bidder_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="Watchlist_listing",
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="current_bid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leading_bid",
                to="auctions.bid",
            ),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
