# Generated by Django 5.1.4 on 2025-02-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_remove_bid_watchlist_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listing",
            name="current_bid",
        ),
        migrations.RemoveField(
            model_name="auction_listing",
            name="owner",
        ),
        migrations.AddField(
            model_name="bid",
            name="Watchlist_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.auction_listing",
            ),
        ),
    ]
