# Generated by Django 5.1.4 on 2025-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_auction_listing_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="owner",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
