# Generated by Django 5.1.4 on 2025-02-07 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_auction_listing_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listing",
            name="owner",
        ),
    ]
