# Generated by Django 5.1.4 on 2025-02-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0014_remove_bid_watchlist_listing_auction_listing_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction_list",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list",
                to="auctions.auction_listing",
            ),
        ),
    ]
