# Generated by Django 5.1.4 on 2025-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_alter_bid_auction_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="auction_list",
        ),
    ]
