# Generated by Django 5.1.4 on 2025-02-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_remove_bid_auction_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list",
                to="auctions.auction_listing",
            ),
        ),
    ]
