# Generated by Django 5.1.4 on 2025-02-27 18:36

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_create_posting_comment_followers_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="followers",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.expressions.Case,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
