# Generated by Django 5.1.4 on 2025-02-27 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_followers_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followers",
            unique_together={("user", "following", "follower")},
        ),
    ]
