# Generated by Django 5.1.4 on 2025-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_followers_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
