# Generated by Django 5.1.4 on 2025-03-03 13:39

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_alter_followers_follower_alter_followers_following"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followers",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="followers",
            name="follower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.expressions.Case,
                related_name="following_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="followers",
            name="following",
        ),
        migrations.RemoveField(
            model_name="like",
            name="like",
        ),
    ]
