# Generated by Django 5.1.4 on 2025-03-03 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_alter_followers_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followers",
            unique_together={("user", "follower")},
        ),
    ]
