# Generated by Django 5.1.4 on 2025-03-05 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0009_alter_followers_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
